### PR TITLE
Remove incorrect whitespace in generated code

### PR DESCRIPTION
**Pull request by robloo**
This was tripping up Code Analyzers so might as well be fixed

### CODE REVIEW

**Review by worldbeater — APPROVED** [review]
Thanks for the fix! Going to 🚢 this

**Comment by worldbeater** [comment]
Approval tests seem to be failing due to the change in whitespace, going to fix those soon.

**Comment by worldbeater** [comment]
Most likely we are hitting https://github.com/actions/first-interaction/issues/10 so going to re-trigger the build in a separate PR soon.

**Comment by robloo** [comment]
I missed the test file, thanks for updating!

**Pull request merged**
